test ci

diff --git a/.github/workflows/vpc-ci-dev-create.yml b/.github/workflows/vpc-ci-dev-create.yml
--- a/.github/workflows/vpc-ci-dev-create.yml
+++ b/.github/workflows/vpc-ci-dev-create.yml
@@ -31,25 +31,28 @@ jobs:
           aws-region: eu-central-1
           role-to-assume: arn:aws:iam::${{env.AWS_ACCOUNT_NUMBER}}:role/github-actions-role
           role-session-name: Session-GitHubActions
-      - name: Setup Terraform with specified version on the runner
-        uses: hashicorp/setup-terraform@v2
-        # with:
-        #   terraform_version: 1.4.6
-      - name: Terraform format
-        id: fmt
-        run: terraform fmt -check
-      - name: Terraform init
-        id: init
-        run: terraform init
-      - name: Terraform validate
-        id: validate
-        run: terraform validate
-      - name: Terraform plan
-        id: plan
-        run: terraform plan -var-file=./dev/terraform.tfvars -no-color -input=false
-        continue-on-error: true
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
-      # - name: Terraform Apply
-      #   run: terraform apply -var-file=./dev/terraform.tfvars -auto-approve -input=false
+      - name: Get AWS Caller Identity
+        run: |
+          aws sts get-caller-identity --output json
+      # - name: Setup Terraform with specified version on the runner
+      #   uses: hashicorp/setup-terraform@v2
+      #   # with:
+      #   #   terraform_version: 1.4.6
+      # - name: Terraform format
+      #   id: fmt
+      #   run: terraform fmt -check
+      # - name: Terraform init
+      #   id: init
+      #   run: terraform init
+      # - name: Terraform validate
+      #   id: validate
+      #   run: terraform validate
+      # - name: Terraform plan
+      #   id: plan
+      #   run: terraform plan -var-file=./dev/terraform.tfvars -no-color -input=false
+      #   continue-on-error: true
+      # - name: Terraform Plan Status
+      #   if: steps.plan.outcome == 'failure'
+      #   run: exit 1
+      # # - name: Terraform Apply
+      # #   run: terraform apply -var-file=./dev/terraform.tfvars -auto-approve -input=false
